### ISSUE TITLE
Doesn't support Co-Authors Plus

### ISSUE THREAD

**Issue by garretthyder** [Section214/Username-Changer#1]
Hello,

I found your plugin very useful, one limitation I've run into sadly is with Co-Authors Plus. Doing a username change drops all the authorship associations.

Thanks

**Comment by garretthyder** [comment]
I've also opened this on the WP Support Forum in the hopes of some assistance;
https://wordpress.org/support/topic/support-for-co-authors-plus?replies=1#post-7108510

**Comment by evertiro** [comment]
I'm not really familiar with Co-Authors Plus, but at a glance that's probably because Co-Authors stores data based on username instead of user ID. I'll see if there's a way to get around this. Worst case... I'll fork Co-Authors Plus and do it right!

**Comment by garretthyder** [comment]
Thanks @ghost1227, I've been able to amend the plugin to support Co-Authors Plus. I'm just finishing my testing and then I'll fork the plugin and make a pull request.

**Comment by garretthyder** [comment]
Hey @ghost1227 please review and test would love your feedback. Cheers

**Comment by evertiro** [comment]
Reviewing, please leave the initial ticket open until it's merged or I'll lose track of it! :)

**Comment by garretthyder** [comment]
Thanks @ghost1227 , sorry bout that
