### ISSUE TITLE
Feature Request - Change Username from Profile

### ISSUE THREAD

**Issue by garretthyder** [Section214/Username-Changer#3]
Hello,

Would love to see the plugin updated so the message 'Usernames cannot be changed' on the user profile is removed and the Username field made editable or at the least a link beside it provided to take you to the Username Changer page for that user.
![screen shot 2015-06-24 at 6 57 42 pm](https://cloud.githubusercontent.com/assets/8726005/8345391/2fff1cd8-1aa3-11e5-87d8-9ca72ad044a5.png)

Much appreciated,
Cheers

**Comment by evertiro** [comment]
Good idea! I'll add that!

**Comment by garretthyder** [comment]
Thanks @ghost1227

**Comment by evertiro** [comment]
@garrett-eclipse Ping me when you're around, I want to discuss an idea with you.

**Comment by garretthyder** [comment]
Hey @ghost1227, how can I help?

**Comment by evertiro** [comment]
So I was thinking that it might be a worthwhile option to get rid of the current interface altogether and JUST rely on a reworked profile page. It'd be cleaner, and allow the addition of things like settings to allow configurable permissions required to edit your own username. Thoughts? What other cool things could I add? What other settings could be added?

**Comment by garretthyder** [comment]
Cool @ghost1227 I love the idea, makes alot of sense too. There really isn't a need for the current interface. Could provide a Settings page and have the actual changing of usernames handled from peoples profiles just like the email and name is standardly handled. I feel would fit into the native WP UI better too. Drop that user link on the user listing as unneeded along with that page.

On the settings page you could provide some pretty useful capabilities;
1. Role Permissions so only select roles have the ability to change username, all other roles wouldn't even realize it was an option. \* See wpvn settings 'User must be at least this level...'
![user role settingsy](https://s.w.org/plugins/wpvn-username-changer/screenshot-1.png?r=1187378)
2. Checkbox to disable Coauthor Plus integration.
3. Checkbox to disable Buddypress integration.
4. Checkbox to disable Woocommerce integration. 
*I say disable for integrations as I feel if the plugin is installed the integration should automatically function unless the user doesn't want that functionality. May omit required ones like coauthors plus where disabling could result in issues. Buddypress/Woocommerce would make more sense as you'd be enabling/disabling the ability to change username from their profile pages (Buddypress = xProfile, Woocommerce = My Account).
5. You could provide language support.
6. Username Requirements, can set-up requirements on usernames such as length.

That's about all I can think of, aside from supporting various plugins that have user profiles or tie into using the username such as coauthors did there's not alot one would want from the plugin aside from allowing people to change their username.

Hope that's helpful, if I think of anything else will hit you up.

Cheers

**Comment by evertiro** [comment]
It already supports internationalization, but this will be the first version that ships with the necessary .pot file. Good ideas though! I'm thinking of making it more 'modular', allowing extension to work with other products be adding/removing bundled modules.

**Comment by garretthyder** [comment]
I guess another useful thing is when changing other users aside from yourself you may want a notification sent to them indicating the change. So you could have a email template customizable with something like mailchimp mergetags for the fields and a checkbox to enable/disable the sending of notifications on username changes.  Could have it either be a global setting on the settings page or a checkbox right below the username field on the profile that says notify user of change, kind of like what's on the New User page in WP;

Single Site;
![screen shot 2015-06-25 at 1 49 02 am](https://cloud.githubusercontent.com/assets/8726005/8350681/697c8b38-1adc-11e5-84b6-3c4254ca3ba7.png)

Multisite:
![screen shot 2015-06-25 at 1 48 11 am](https://cloud.githubusercontent.com/assets/8726005/8350678/66300752-1adc-11e5-8014-558eb91c9662.png)

**Comment by garretthyder** [comment]
Awesome, I'm definitely a fan of modular. That works great when enabling support for Woocommerce and Buddypress but some plugins that would result in broken functionality like Coauthors Plus did may be needed as an integral piece that's enabled via the 'if plugin is installed' logic.

**Comment by garretthyder** [comment]
Let me know if you want any help with updates @ghost1227

**Comment by evertiro** [comment]
@garrett-eclipse This is resolved with the pending 3.0.0 release. I've already got an open issue for BuddyPress support, feel free to open issues for any other integrations you thing are worthwhile.

**Comment by garretthyder** [comment]
Awesome thanks @ghost1227

**Comment by evertiro** [comment]
No problem! Sorry for the (stupidly long) delay!
