### ISSUE TITLE
Update to support 4.6

### ISSUE THREAD

**Issue by garretthyder** [Section214/Username-Changer#7]
With WP 4.6 the get_currentuserinfo function was deprecated to be replaced by wp_get_current_user.
Please update the plugin accordingly.
Support Ticket - https://wordpress.org/support/topic/wordpress-46-deprecated-get_currentuserinfo?replies=1
Thanks
Note: Rather than setting up the current_user global and calling get_currentuserinfo simply switch to a local current_user variable defined as follows;
`$current_user = wp_get_current_user();`

**Comment by evertiro** [comment]
Resolved with the 2.1.0 release.
